name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_isocalendar: yes
          plugin_isocalendar_limit: 52
          plugin_isocalendar_sections: commits,issues,prs,reviews,stars,forks,clones,views

          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_colors: '#4584b6,#ffdf5d,#616163,#4e8e4e,#356862,#e38844'

          plugin_achievements: no
          plugin_activity: no

          use_template: yes
          template: classic

          base_color: '1a1b26'
          base_theme: high-contrast

          text_color: 'FAFAFA'
          label_color: '66D9EF'
          badge_color: 'A6E22E'
          icon_color: 'E6DB74'

          animations: yes

          output_action: commit